# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38c1d02b3be17dc8222c3560ee5af1a024a02e276ab2fe7e5b5b0262d9c335c1ce06b49f7a23c196ae56230ed04ee3706ec1a535a58bb4870628ce7ca47c7eb1

test:
  secret_key_base: 427bcd03cfe405abd61970cdc9c146ff6b8cdb92b6b6bf104ededcf3bd4d8a06f45a38a7f703b26f000340c8ac7e39ba4d866ae8d0017b279c5b8a8e6ea73191

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
